--- #YAML:1.0
name:                Text-Darts
version:             0.04
abstract:            Perl interface to DARTS by Taku Kudoh
license:             ~
author:              
    - Dan <dankogai@dan.co.jp>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
